#include <stdio.h>

//请根据主程序流程，补全此函数
//冰雹产生并输出函数
//注意：输出每个冰雹数时，请按5位对齐输出
void hailstone(int n) 
{
    printf("Hailstone generated by %d:\n",n);
    /**********  Begin **********/
    scanf("%d",&n);
    int a,b,i=1;
    a=n;
    printf("%5d",a);
    while(a!=1){
        if(a%2==0)
        b=a/2;
        else
        b=3*a+1;
        printf("%5d",b);
        i++;
        if(i%6==0)
        printf("\n");
        a=b;
    }






    /**********  End  **********/
    //printf("%5d\n",n);
	printf("\nNumber of hailstone generated:%d",i);
}