name: Update STAR-HISTORY Daily

on:
  schedule:
    - cron: '0 12 * * *'  # 每天 UTC 时间 12:00 (北京时间 20:00) 运行
  workflow_dispatch:       # 允许手动触发

jobs:
  update-STAR-HISTORY:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download STAR-HISTORY PNG
      run: |
        curl -s -o STAR-HISTORY.png "https://api.star-history.com/svg?repos=nuyoahwjl/HUST-CS&type=Timeline"

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add STAR-HISTORY.png
        git diff --quiet && git diff --staged --quiet || git commit -m "Update STAR-HISTORY.png"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/Nuyoahwjl/HUST-CS.git HEAD:main
